package com.proj1.model;
// Generated Dec 3, 2015 10:04:36 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DeliveryTypes generated by hbm2java
 */
@Entity
@Table(name = "delivery_types", catalog = "giftshop")
public class DeliveryTypes implements java.io.Serializable {

	private Integer deliveryTypeId;
	private String deliveryType;
	private float chargeFactor;
	private Set<DeliveryDetails> deliveryDetailses = new HashSet<DeliveryDetails>(0);

	public DeliveryTypes() {
	}

	public DeliveryTypes(float chargeFactor) {
		this.chargeFactor = chargeFactor;
	}

	public DeliveryTypes(String deliveryType, float chargeFactor, Set<DeliveryDetails> deliveryDetailses) {
		this.deliveryType = deliveryType;
		this.chargeFactor = chargeFactor;
		this.deliveryDetailses = deliveryDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "delivery_type_id", unique = true, nullable = false)
	public Integer getDeliveryTypeId() {
		return this.deliveryTypeId;
	}

	public void setDeliveryTypeId(Integer deliveryTypeId) {
		this.deliveryTypeId = deliveryTypeId;
	}

	@Column(name = "delivery_type", length = 50)
	public String getDeliveryType() {
		return this.deliveryType;
	}

	public void setDeliveryType(String deliveryType) {
		this.deliveryType = deliveryType;
	}

	@Column(name = "charge_factor", nullable = false, precision = 4)
	public float getChargeFactor() {
		return this.chargeFactor;
	}

	public void setChargeFactor(float chargeFactor) {
		this.chargeFactor = chargeFactor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deliveryTypes")
	public Set<DeliveryDetails> getDeliveryDetailses() {
		return this.deliveryDetailses;
	}

	public void setDeliveryDetailses(Set<DeliveryDetails> deliveryDetailses) {
		this.deliveryDetailses = deliveryDetailses;
	}

}
