package com.proj1.model;
// Generated Dec 3, 2015 10:04:36 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * DeliveryDetails generated by hbm2java
 */
@Entity
@Table(name = "delivery_details", catalog = "giftshop")
public class DeliveryDetails implements java.io.Serializable {

	private int deliveryId;
	private Address address;
	private DeliveryTypes deliveryTypes;
	private OrderDetails orderDetails;
	private Date deliveryDate;
	private Date deliveryTime;
	private String occassion;

	public DeliveryDetails() {
	}

	public DeliveryDetails(Address address, OrderDetails orderDetails) {
		this.address = address;
		this.orderDetails = orderDetails;
	}

	public DeliveryDetails(Address address, DeliveryTypes deliveryTypes, OrderDetails orderDetails, Date deliveryDate,
			Date deliveryTime, String occassion) {
		this.address = address;
		this.deliveryTypes = deliveryTypes;
		this.orderDetails = orderDetails;
		this.deliveryDate = deliveryDate;
		this.deliveryTime = deliveryTime;
		this.occassion = occassion;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "orderDetails") )
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "delivery_id", unique = true, nullable = false)
	public int getDeliveryId() {
		return this.deliveryId;
	}

	public void setDeliveryId(int deliveryId) {
		this.deliveryId = deliveryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "address_id", nullable = false)
	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "delivery_type_id")
	public DeliveryTypes getDeliveryTypes() {
		return this.deliveryTypes;
	}

	public void setDeliveryTypes(DeliveryTypes deliveryTypes) {
		this.deliveryTypes = deliveryTypes;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public OrderDetails getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(OrderDetails orderDetails) {
		this.orderDetails = orderDetails;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "delivery_date", length = 10)
	public Date getDeliveryDate() {
		return this.deliveryDate;
	}

	public void setDeliveryDate(Date deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "delivery_time", length = 8)
	public Date getDeliveryTime() {
		return this.deliveryTime;
	}

	public void setDeliveryTime(Date deliveryTime) {
		this.deliveryTime = deliveryTime;
	}

	@Column(name = "occassion", length = 2000)
	public String getOccassion() {
		return this.occassion;
	}

	public void setOccassion(String occassion) {
		this.occassion = occassion;
	}

}
