package com.proj1.model;
// Generated Nov 14, 2015 7:53:22 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DeliveryDetails generated by hbm2java
 */
@Entity
@Table(name = "delivery_details", catalog = "giftshop")
public class DeliveryDetails implements java.io.Serializable {

	private Integer deliveryId;
	private Address address;
	private DeliveryTypes deliveryTypes;
	private Date deliveryDate;
	private Date deliveryTime;
	private String occassion;
	private Set<OrderDetails> orderDetailses = new HashSet<OrderDetails>(0);

	public DeliveryDetails() {
	}

	public DeliveryDetails(Address address) {
		this.address = address;
	}

	public DeliveryDetails(Address address, DeliveryTypes deliveryTypes, Date deliveryDate, Date deliveryTime,
			String occassion, Set<OrderDetails> orderDetailses) {
		this.address = address;
		this.deliveryTypes = deliveryTypes;
		this.deliveryDate = deliveryDate;
		this.deliveryTime = deliveryTime;
		this.occassion = occassion;
		this.orderDetailses = orderDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "delivery_id", unique = true, nullable = false)
	public Integer getDeliveryId() {
		return this.deliveryId;
	}

	public void setDeliveryId(Integer deliveryId) {
		this.deliveryId = deliveryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "address_id", nullable = false)
	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "delivery_type_id")
	public DeliveryTypes getDeliveryTypes() {
		return this.deliveryTypes;
	}

	public void setDeliveryTypes(DeliveryTypes deliveryTypes) {
		this.deliveryTypes = deliveryTypes;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "delivery_date", length = 10)
	public Date getDeliveryDate() {
		return this.deliveryDate;
	}

	public void setDeliveryDate(Date deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "delivery_time", length = 8)
	public Date getDeliveryTime() {
		return this.deliveryTime;
	}

	public void setDeliveryTime(Date deliveryTime) {
		this.deliveryTime = deliveryTime;
	}

	@Column(name = "occassion", length = 2000)
	public String getOccassion() {
		return this.occassion;
	}

	public void setOccassion(String occassion) {
		this.occassion = occassion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deliveryDetails")
	public Set<OrderDetails> getOrderDetailses() {
		return this.orderDetailses;
	}

	public void setOrderDetailses(Set<OrderDetails> orderDetailses) {
		this.orderDetailses = orderDetailses;
	}

}
