package com.proj1.model;
// Generated Nov 14, 2015 7:53:22 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedNativeQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Item generated by hbm2java
 */
@Entity
@NamedNativeQuery(name = "Item.byCategoryId", query = "SELECT item_code, item_name, item_desc, price, category_id, file_name FROM ITEM WHERE category_id = ?", resultClass = Item.class)
@Table(name = "item", catalog = "giftshop")
public class Item implements java.io.Serializable {

	private Integer itemCode;
	private Category category;
	private String itemName;
	private String itemDesc;
	private Float price;
	private String fileName;
	private Set<OrderDetails> orderDetailses = new HashSet<OrderDetails>(0);

	public Item() {
	}

	public Item(Category category, String itemName, String itemDesc, Float price, String fileName,
			Set<OrderDetails> orderDetailses) {
		this.category = category;
		this.itemName = itemName;
		this.itemDesc = itemDesc;
		this.price = price;
		this.fileName = fileName;
		this.orderDetailses = orderDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "item_code", unique = true, nullable = false)
	public Integer getItemCode() {
		return this.itemCode;
	}

	public void setItemCode(Integer itemCode) {
		this.itemCode = itemCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id")
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "item_name", length = 50)
	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	@Column(name = "item_desc", length = 4000)
	public String getItemDesc() {
		return this.itemDesc;
	}

	public void setItemDesc(String itemDesc) {
		this.itemDesc = itemDesc;
	}

	@Column(name = "price", precision = 6)
	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	@Column(name = "file_name", length = 100)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "item")
	public Set<OrderDetails> getOrderDetailses() {
		return this.orderDetailses;
	}

	public void setOrderDetailses(Set<OrderDetails> orderDetailses) {
		this.orderDetailses = orderDetailses;
	}

	@Override
	public String toString() {
		return "Item [itemCode=" + itemCode + ", category=" + category + ", itemName=" + itemName + ", itemDesc="
				+ itemDesc + ", price=" + price + ", fileName=" + fileName + ", orderDetailses=" + orderDetailses + "]";
	}

	
}
