package com.proj1.model;
// Generated Nov 14, 2015 7:53:22 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "message", catalog = "giftshop")
public class Message implements java.io.Serializable {

	private Integer messageId;
	private String messageType;
	private String messageFileName;
	private Set<OrderDetails> orderDetailses = new HashSet<OrderDetails>(0);

	public Message() {
	}

	public Message(String messageFileName) {
		this.messageFileName = messageFileName;
	}

	public Message(String messageType, String messageFileName, Set<OrderDetails> orderDetailses) {
		this.messageType = messageType;
		this.messageFileName = messageFileName;
		this.orderDetailses = orderDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "message_id", unique = true, nullable = false)
	public Integer getMessageId() {
		return this.messageId;
	}

	public void setMessageId(Integer messageId) {
		this.messageId = messageId;
	}

	@Column(name = "message_type", length = 10)
	public String getMessageType() {
		return this.messageType;
	}

	public void setMessageType(String messageType) {
		this.messageType = messageType;
	}

	@Column(name = "message_file_name", nullable = false, length = 100)
	public String getMessageFileName() {
		return this.messageFileName;
	}

	public void setMessageFileName(String messageFileName) {
		this.messageFileName = messageFileName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "message")
	public Set<OrderDetails> getOrderDetailses() {
		return this.orderDetailses;
	}

	public void setOrderDetailses(Set<OrderDetails> orderDetailses) {
		this.orderDetailses = orderDetailses;
	}

}
