package com.proj1.model;
// Generated Dec 3, 2015 10:04:36 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "message", catalog = "giftshop")
public class Message implements java.io.Serializable {

	private int messageId;
	private OrderDetails orderDetails;
	private String messageType;
	private String messageFileName;

	public Message() {
	}

	public Message(OrderDetails orderDetails, String messageFileName) {
		this.orderDetails = orderDetails;
		this.messageFileName = messageFileName;
	}

	public Message(OrderDetails orderDetails, String messageType, String messageFileName) {
		this.orderDetails = orderDetails;
		this.messageType = messageType;
		this.messageFileName = messageFileName;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "orderDetails") )
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "message_id", unique = true, nullable = false)
	public int getMessageId() {
		return this.messageId;
	}

	public void setMessageId(int messageId) {
		this.messageId = messageId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public OrderDetails getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(OrderDetails orderDetails) {
		this.orderDetails = orderDetails;
	}

	@Column(name = "message_type", length = 10)
	public String getMessageType() {
		return this.messageType;
	}

	public void setMessageType(String messageType) {
		this.messageType = messageType;
	}

	@Column(name = "message_file_name", nullable = false, length = 100)
	public String getMessageFileName() {
		return this.messageFileName;
	}

	public void setMessageFileName(String messageFileName) {
		this.messageFileName = messageFileName;
	}

}
