package com.proj1.model;
// Generated Nov 14, 2015 7:53:22 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderDetails generated by hbm2java
 */
@Entity
@Table(name = "order_details", catalog = "giftshop")
public class OrderDetails implements java.io.Serializable {

	private Integer orderId;
	private DeliveryDetails deliveryDetails;
	private Item item;
	private Message message;
	private User user;

	public OrderDetails() {
	}

	public OrderDetails(DeliveryDetails deliveryDetails, Item item) {
		this.deliveryDetails = deliveryDetails;
		this.item = item;
	}

	public OrderDetails(DeliveryDetails deliveryDetails, Item item, Message message, User user) {
		this.deliveryDetails = deliveryDetails;
		this.item = item;
		this.message = message;
		this.user = user;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "order_id", unique = true, nullable = false)
	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "delivery_id", nullable = false)
	public DeliveryDetails getDeliveryDetails() {
		return this.deliveryDetails;
	}

	public void setDeliveryDetails(DeliveryDetails deliveryDetails) {
		this.deliveryDetails = deliveryDetails;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_code", nullable = false)
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "message_id")
	public Message getMessage() {
		return this.message;
	}

	public void setMessage(Message message) {
		this.message = message;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sender_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
