package com.proj1.model;
// Generated Dec 3, 2015 10:04:36 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * OrderDetails generated by hbm2java
 */
@Entity
@Table(name = "order_details", catalog = "giftshop")
public class OrderDetails implements java.io.Serializable {

	private Integer orderId;
	private User user;
	private Set<Item> items = new HashSet<Item>(0);
	private DeliveryDetails deliveryDetails;
	private Message message;

	public OrderDetails() {
	}

	public OrderDetails(User user, Set<Item> items, DeliveryDetails deliveryDetails, Message message) {
		this.user = user;
		this.items = items;
		this.deliveryDetails = deliveryDetails;
		this.message = message;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "order_id", unique = true, nullable = false)
	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sender_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "order_details_item", catalog = "giftshop", joinColumns = {
			@JoinColumn(name = "order_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "item_code", nullable = false, updatable = false) })
	public Set<Item> getItems() {
		return this.items;
	}

	public void setItems(Set<Item> items) {
		this.items = items;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "orderDetails")
	public DeliveryDetails getDeliveryDetails() {
		return this.deliveryDetails;
	}

	public void setDeliveryDetails(DeliveryDetails deliveryDetails) {
		this.deliveryDetails = deliveryDetails;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "orderDetails")
	public Message getMessage() {
		return this.message;
	}

	public void setMessage(Message message) {
		this.message = message;
	}

}
